spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    username: sa
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
  h2:
    console:
      path: /h2-console
      enabled: true