server:
  port: 8080

spring:
  config:
    import: application-secret.yml
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    username: sa
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
  h2:
    console:
      path: /h2-console
      enabled: true
  application:
    name: email-sender
  mail:
    host: smtp.gmail.com
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

  logging:
    level:
      'org.hibernate.SQL': debug
      'org.hibernate.orm.jdbc.bind': trace
      'org.springframework.security.web': trace

security:
  jwt:
    secret-key: ${jwt.secret-key}
    expiration-time: 3600000
