server:
  port: 8080

spring:
  h2:
    path: /h2-console
    enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    password: 1234
    username: sa
    hikari:
      jdbc-url: jdbc:h2:~/local

  application:
    name: email-sender
  mail:
    host: smtp.gmail.com
    username: nevertheless113@gmail.com
    password: urhuscpylknauzey
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000



  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  logging:
    level:
      'org.hibernate.SQL': debug
      'org.hibernate.orm.jdbc.bind': trace
      'org.springframework.security.web': trace

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
