jwt:
  secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

spring:
  mail:
    username: nevertheless113@gmail.com
    password: urhuscpylknauzey

cloud:
  aws:
    credentials:
      accessKey: AKIA6IY35VYAWNPJIAH7
      secretKey: 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