server:
  port: 8080
spring:
  profiles:
    active: dev
  config:
    import: application-secret.yml
  application:
    name: email-sender
  mail:
    host: smtp.gmail.com
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
logging:
  level:
    'org.hibernate.SQL': debug
    'org.hibernate.orm.jdbc.bind': trace
    'org.springframework.security.web': trace
security:
  jwt:
    secret-key: ${jwt.secret-key}
    expiration-time: 86400000
cloud:
  aws:
    credentials:
      accessKey: ${cloud.aws.credentials.accessKey}
      secretKey: ${cloud.aws.credentials.secretKey}
    s3:
      bucket: autoever-blog
      dir: image
    region:
      static: ap-northeast-2
    stack:
      auto: false