name: Spring Boot CI/CD to Oracle Cloud

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew bootJar
      
    - name: Copy jar file via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ORACLE_CLOUD_HOST }}
        username: ${{ secrets.ORACLE_CLOUD_USER }}
        key: ${{ secrets.ORACLE_CLOUD_SSH_KEY }}
        source: "build/libs/*.jar"
        target: "~/app"
        strip_components: 2

    - name: Deploy to Oracle Cloud
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ORACLE_CLOUD_HOST }}
        username: ${{ secrets.ORACLE_CLOUD_USER }}
        key: ${{ secrets.ORACLE_CLOUD_SSH_KEY }}
        script: |
          # 기존 프로세스 종료
          pid=$(pgrep -f your-app-name.jar) && kill -9 $pid || true
          
          # 새로운 jar 파일 실행
          cd ~/app
          nohup java -jar -Dspring.profiles.active=prod *.jar > app.log 2>&1 &
